name: DocEditor

services:

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
      # - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    # develop:
    #   watch:
    #     - action: rebuild
    #       path: ./nginx/nginx.conf

  frontend:
    build:
      context: ./frontend
      args:
        - INTERNAL_JWT_SECRET
        - SHARED_JWT_SECRET
        - PUBLIC_GOOGLE_CLIENT_ID
    # expose doesn't open the port, it is only for documentation
    expose:
      - "3000"
    env_file:
      - ./frontend/.env
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /code/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  backend:
    build:
      context: ./backend
    expose:
      - "8000"
    env_file:
      - ./backend/.env
    develop:
      watch:
        - action: sync
          path: ./backend/app
          target: /code/app
          ignore:
            - __pycache__/
        - action: rebuild
          path: requirements.txt
